dataset_eval_params:
  im_size : 224
  precrop_size : 256
  im_channels : 3
  mean : [0.485, 0.456, 0.406]
  std  : [0.229, 0.224, 0.225]
  interpolation_mode : BICUBIC

eval:
  val_batch_size : 16
  num_workers : 2
  pin_memory : True

