name: Lint

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/reusable-setup.yml
    with:
      python-version: "3.13"

    steps:
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 black

      - name: Run Black
        run: black --check .

      - name: Run Flake8
        run: flake8 .
